package project1.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import project1.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.06.06 20:38:53 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class GameSessionTest {



  // Generated by ComTest BEGIN
  /** testGetAnswer63 */
  @Test
  public void testGetAnswer63() {    // GameSession: 63
    GameSession answerTest = new GameSession(); 
    answerTest.setAnswer(14); assertEquals("From: GameSession line: 65", 14, answerTest.getAnswer()); 
    answerTest.setAnswer(2); assertEquals("From: GameSession line: 66", 2, answerTest.getAnswer()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetScore84 */
  @Test
  public void testGetScore84() {    // GameSession: 84
    GameSession scoreTest = new GameSession(); 
    assertEquals("From: GameSession line: 86", 0, scoreTest.getScore()); 
    scoreTest.setScore(2); assertEquals("From: GameSession line: 88", 2, scoreTest.getScore()); 
    scoreTest.setScore(-4); assertEquals("From: GameSession line: 89", 2, scoreTest.getScore()); 
    scoreTest.setScore(0); assertEquals("From: GameSession line: 90", 2, scoreTest.getScore()); 
  } // Generated by ComTest END
}