package project1.test;
// Generated by ComTest BEGIN
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import static org.junit.Assert.*;
import org.junit.*;
import project1.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.06.29 10:45:43 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class InputHandlerTest {



  // Generated by ComTest BEGIN
  /** testReadInt44 */
  @Test
  public void testReadInt44() {    // InputHandler: 44
    InputStream originalSource = System.in; 
    try {
    System.setIn(new ByteArrayInputStream("3\n".getBytes())); 
    InputHandler ih = new InputHandler(); 
    assertEquals(3, ih.readInt()); 
    System.setIn(new ByteArrayInputStream("au7\n7\n".getBytes())); 
    ih = new InputHandler(); 
    assertEquals(7, ih.readInt()); 
    ih.closeTheScanner(); 
    } finally {
    System.setIn(originalSource); 
    }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testReadPlayerName97 */
  @Test
  public void testReadPlayerName97() {    // InputHandler: 97
    InputStream originalSource = System.in; 
    try {
    System.setIn(new ByteArrayInputStream("neko\n2\n".getBytes())); 
    InputHandler reader = new InputHandler(); 
    assertEquals("neko", reader.readPlayerName()); 
    assertEquals("2", reader.readPlayerName()); 
    reader.closeTheScanner(); 
    } finally {
    System.setIn(originalSource); 
    }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testWantToPlay122 */
  @Test
  public void testWantToPlay122() {    // InputHandler: 122
    InputStream originalIn = System.in; 
    try {
    System.setIn(new ByteArrayInputStream("1\n".getBytes())); 
    InputHandler ih = new InputHandler(); 
    assertTrue(ih.wantToPlay()); 
    System.setIn(new ByteArrayInputStream("0\n".getBytes())); 
    ih = new InputHandler(); 
    assertFalse(ih.wantToPlay()); 
    } finally {
    System.setIn(originalIn); 
    }
  } // Generated by ComTest END
}