package project1.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import project1.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.06.06 20:15:28 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PlayerTest {



  // Generated by ComTest BEGIN
  /** testPlayer25 */
  @Test
  public void testPlayer25() {    // Player: 25
    Player a = new Player("a"); 
    assertEquals("From: Player line: 27", "Player name: A | Best score so far: 10000", a.toString()); 
    Player b = new Player("aB"); 
    assertEquals("From: Player line: 29", "Player name: AB | Best score so far: 10000", b.toString()); 
    Player c = new Player(); 
    assertEquals("From: Player line: 31", "Player name: NEKO | Best score so far: 10000", c.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetName62 */
  @Test
  public void testGetName62() {    // Player: 62
    Player nameTest1 = new Player(); 
    assertEquals("From: Player line: 64", "NEKO", nameTest1.getName()); 
    Player nameTest2 = new Player("uyHu"); 
    assertEquals("From: Player line: 66", "UYHU", nameTest2.getName()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetBestScore111 */
  @Test
  public void testGetBestScore111() {    // Player: 111
    Player scoreTest1 = new Player(); 
    assertEquals("From: Player line: 113", 10000, scoreTest1.getBestScore()); 
    scoreTest1.setBestScore(10); assertEquals("From: Player line: 114", 10, scoreTest1.getBestScore()); 
    scoreTest1.setBestScore(24); assertEquals("From: Player line: 115", 10, scoreTest1.getBestScore()); 
    scoreTest1.setBestScore(-5); assertEquals("From: Player line: 116", 10, scoreTest1.getBestScore()); 
  } // Generated by ComTest END
}