package project1.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import project1.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2025.06.06 11:56:12 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class PlayerTest {


  // Generated by ComTest BEGIN
  /** testPlayer25 */
  @Test
  public void testPlayer25() {    // Player: 25
    Player a = new Player("a"); 
    assertEquals("From: Player line: 27", "Player name: A | Best score so far: 10000", a.toString()); 
  } // Generated by ComTest END
}